# Generated by Django 4.0 on 2022-07-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('numofproduct', models.IntegerField()),
                ('startingdate', models.DateTimeField()),
                ('daycount', models.IntegerField()),
                ('note', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('changeddate', models.DateField(auto_now=True)),
                ('auth_user', models.CharField(max_length=45)),
            ],
        ),
    ]
