# Generated by Django 4.0 on 2022-07-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='changeddate',
        ),
        migrations.AlterField(
            model_name='orders',
            name='daycount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
