# Generated by Django 4.0 on 2022-07-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orders_auth_user_remove_orders_changeddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='daycount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kurumada Geçen Gün'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Kullanıcı Adı'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Not'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='numofproduct',
            field=models.IntegerField(verbose_name='Koli Adeti'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='startingdate',
            field=models.DateField(verbose_name='Resim Atma Tarihi'),
        ),
    ]
