# Generated by Django 4.0 on 2022-07-09 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_daycount_alter_orders_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='appointmentdate',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Randevu Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=254, verbose_name='Mail'),
            preserve_default=False,
        ),
    ]
