# Generated by Django 4.0 on 2022-07-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orders_appointmentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='userid',
            field=models.IntegerField(default=1, verbose_name='Kullanıcı Id'),
            preserve_default=False,
        ),
    ]
