# Generated by Django 4.0 on 2022-07-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='remainingday',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kalan Gün'),
        ),
    ]
