# Generated by Django 4.0 on 2022-07-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='orders',
        ),
        migrations.AddField(
            model_name='appointment',
            name='order',
            field=models.ManyToManyField(to='orders.orders'),
        ),
    ]
