# Generated by Django 4.0 on 2022-07-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_appointment_totalproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointment',
        ),
    ]
